eq_test: EQwindow.cpp shader_utils.cpp
		g++ EQwindow.cpp shader_utils.cpp -o eq_test.o -w -lGL -lglut -lGLEW
shader_test: window.cpp shader_utils.cpp
		g++ window.cpp shader_utils.cpp -o shader_test.o -lGL -lglut -lGLEW
